## Numpy

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4,5]

In [3]:
arr=np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

## Multidimesional array

In [8]:
l1=[1,2,3,4,5]
l2=[10,11,23,34,35]
l3=[12,32,546,657,3]

In [9]:
arr=np.array([l1,l2,l3])

In [10]:
print(arr)

[[  1   2   3   4   5]
 [ 10  11  23  34  35]
 [ 12  32 546 657   3]]


In [13]:
arr.shape # defined the no of rows and columns of the arr

(3, 5)

In [14]:
arr.reshape(5,3) # changes the structure of rows and columns of arr

array([[  1,   2,   3],
       [  4,   5,  10],
       [ 11,  23,  34],
       [ 35,  12,  32],
       [546, 657,   3]])

## Indexing in array

In [15]:
arr=np.array([1,2,3,4,5,6,7])

In [16]:
arr[3]

np.int64(4)

In [17]:
print(arr[3])

4


In [18]:
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [20]:
print(arr[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(arr[0:2,0:2])

[[1 2]
 [5 6]]


In [25]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [26]:
arr = np.arange(1, 6)
print(arr)

[1 2 3 4 5]


In [27]:
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


## Copy function and broadcasting

In [30]:
arr=np.array([1,2,3,4,5,6,7,8])

In [31]:
arr[3:]=100

In [32]:
print(arr)

[  1   2   3 100 100 100 100 100]


In [33]:
arr1=arr

In [37]:
arr1[3:]=100 # updates the second array also

In [35]:
print(arr1)

[  1   2   3 100 100 100 100 100]


In [36]:
print(arr)

[  1   2   3 100 100 100 100 100]


In [43]:
arr1=arr.copy() # This will create the copy array and will not share the same memory address

In [40]:
arr1[3:]=1000

In [41]:
print(arr1)

[   1    2    3 1000 1000 1000 1000 1000]


In [42]:
print(arr)

[  1   2   3 100 100 100 100 100]


In [45]:
val=2

arr*2

array([  2,   4,   6, 200, 200, 200, 200, 200])

In [47]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
# random

np.random.rand(2,2)

array([[0.38739708, 0.95102558],
       [0.52898578, 0.18474594]])

In [49]:
np.random.randn(2,2)

array([[ 0.62478893,  0.33228703],
       [ 0.48355573, -0.75217047]])

In [50]:
np.random.randint(0,100,8)

array([93,  6, 71, 48, 37, 98, 90, 13])

In [51]:
np.random.randint(0,100,8).reshape(2,4)

array([[ 7, 55, 72, 75],
       [20, 44, 56,  5]])